test-implementation:
    - cypress/**
    - __test__/**

features_update:
    - app/**
    - components/**

workflow-update/CI&CD_development:
    - .github/**/*

core_update/Build_update:
    - public/**
    - .**
