name: Build NextApp and Deploy

on:
    push:
        branches: [main, CD-deployment]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x, 21.x]

        steps:
            - uses: actions/checkout@v4
            - name: build nextjs app
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm test
            - run: npm run build --if-present

            - name: connecting to Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DOGDB_HOST}}
                  username: ${{ secrets.DOGDB_USERNAME }}
                  port: ${{ secrets.DOGDB_PORT }}
                  key: ${{ secrets.DOGDB_PRIVATE_SSHKEY }}
                  source: '.'
                  #   source: '.,!node_modules'
                  target: ${{secrets.DOGDB_PREVIEW_FRONTEND_URL}}
            - name: Executing remote command
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DOGDB_HOST}}
                  username: ${{ secrets.DOGDB_USERNAME }}
                  port: ${{ secrets.DOGDB_PORT }}
                  key: ${{ secrets.DOGDB_PRIVATE_SSHKEY }}
                  #   if: ${{ !secrets.DOGDB_PREVIEW_FRONTEND_FOLDER_NAME }}
                  #   script: git pull
                  #   if: ${{ secrets.DOGDB_PREVIEW_FRONTEND_FOLDER_NAME }}
                  script: git clone https://github.com/dogdb-org/dogdb-frontend.git ${{ secrets.DOGDB_PREVIEW_FRONTEND_FOLDER_NAME }}
