name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: DogDB 
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.DOGDB_HOST}}
        USERNAME: ${{ secrets.DOGDB_USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.DOGDB_SSHKEY }}
      with:
        source: "."
        target: "/dogdb"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: ls
