name: Build NextApp and Deploy

on:
    push:
        branches: [main, CD-deployment]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x, 20.x, 21.x]

        steps:
            - uses: actions/checkout@v4
            - name: build nextjs app
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test

            - name: connecting to Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DOGDB_HOST}}
                  username: ${{ secrets.DOGDB_USERNAME }}
                  port: ${{ secrets.DOGDB_PORT }}
                  key: ${{ secrets.DOGDB_PRIVATE_SSHKEY }}
                  source: '.,!node_modules'
                  target: '~/home/elidakirigo/test_dogdb'
            - name: Executing remote command
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DOGDB_HOST}}
                  username: ${{ secrets.DOGDB_USERNAME }}
                  port: ${{ secrets.DOGDB_PORT }}
                  key: ${{ secrets.DOGDB_PRIVATE_SSHKEY }}
                  script: ls
