name: Greet Contributors
on:
    fork:
    push:
        branches: [main]
    issues:
        types: [opened]
    issue_comment:
        types: [created]
    pull_request_target:
        types: [opened]
    pull_request_review_comment:
        types: [created]

jobs:
    welcome:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              # - uses: dogdb
              with:
                  # github-token: ${{ secrets.GITHUB_TOKEN }}
                  issue-message: '<h3>Hey! thank you for opening an Issue 🎉.</h3>'
                  pr-message: '<h3>Hey! thank you for opening a Pull Request 🎉.</h3>'
                  footer: 'Thank you for contributing to DogDB, Happy, Open Source!</b>'
