name: Build NextApp and Deploy

on:
    push:
        branches: [main, CD-deployment]

jobs:
    build:
        runs-on: self-hosted
        strategy:
            matrix:
                node-version: [18.19.0]

        steps:
            - uses: actions/checkout@v4
            - name: npm run , test and build next app
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm test
            - run: npm run build --if-present
